// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tmutzzzwmdilpsnjohyf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRtdXR6enp3bWRpbHBzbmpvaHlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyMzQ3MTgsImV4cCI6MjA3MjgxMDcxOH0.7IWxaQiH4iojKPRNgONISAia8Ll_YaJ-cQYNQM5-yr8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});