// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hzzaqccldfkhwvvtzdmq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh6emFxY2NsZGZraHd2dnR6ZG1xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczNTA3NzEsImV4cCI6MjA3MjkyNjc3MX0.VxTFPaTVXLHNx9eIWBCBc_ab_7950pg4hq2wXc0wgmk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});